### ISSUE TITLE
OSError: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by nab138** [scumjr/cameo#2]
I'm running elementary OS 5.1.7 Hera. Tried to install cameo and on startup it says
"Permission denied", so i tried with sudo and it failed
```
nicholas@NICHOLAS-PC:~/cameo$ sudo modprobe v4l2loopback
nicholas@NICHOLAS-PC:~/cameo$ ./cameo.py
09:19:42.691:root: Frames per second: 30.0
Traceback (most recent call last):
  File "./cameo.py", line 147, in <module>
    main(args.input, args.output, args.flip, args.thumbnail)
  File "./cameo.py", line 93, in main
    video_out = open_video_out(camera_out, width, height)
  File "./cameo.py", line 68, in open_video_out
    video_out = open("/dev/video{camera_out}", "wb")
PermissionError: [Errno 13] Permission denied: '/dev/video{camera_out}'
nicholas@NICHOLAS-PC:~/cameo$ sudo modprobe v4l2loopback
nicholas@NICHOLAS-PC:~/cameo$ sudo ./cameo.py
09:19:47.298:root: Frames per second: 30.0
Traceback (most recent call last):
  File "./cameo.py", line 147, in <module>
    main(args.input, args.output, args.flip, args.thumbnail)
  File "./cameo.py", line 93, in main
    video_out = open_video_out(camera_out, width, height)
  File "./cameo.py", line 71, in open_video_out
    ret = fcntl.ioctl(video_out.fileno(), VIDIOC_S_FMT, request)
OSError: [Errno 25] Inappropriate ioctl for device
```

**Comment by nab138** [comment]
In case it helps, i have a HP Eliteone All-in-one PC.

**Comment by scumjr** [comment]
I guess the [VIDIOC_S_FMT](https://github.com/scumjr/cameo/blob/3bdcc1c3f01a01ab8b2cb41e934a505dc6afd0ba/cameo.py#L17) ioctl or/and the [v4l2_pix_format](https://github.com/scumjr/cameo/blob/3bdcc1c3f01a01ab8b2cb41e934a505dc6afd0ba/cameo.py#L9-L34) [structure](https://www.kernel.org/doc/html/v5.4/media/uapi/v4l/vidioc-g-fmt.html) isn't valid with your kernel version.

Feel free to open a PR if you manage to fix it.
